export const contractAddress = "0xF1c90240B80Ea341044265ADecA9299681eca99c"
export const abi = [
	{
	   "inputs":[
		  
	   ],
	   "stateMutability":"nonpayable",
	   "type":"constructor"
	},
	{
	   "anonymous":false,
	   "inputs":[
		  {
			 "indexed":true,
			 "internalType":"address",
			 "name":"previousOwner",
			 "type":"address"
		  },
		  {
			 "indexed":true,
			 "internalType":"address",
			 "name":"newOwner",
			 "type":"address"
		  }
	   ],
	   "name":"OwnershipTransferred",
	   "type":"event"
	},
	{
	   "inputs":[
		  {
			 "internalType":"address",
			 "name":"",
			 "type":"address"
		  }
	   ],
	   "name":"BuyerPhase",
	   "outputs":[
		  {
			 "internalType":"bool",
			 "name":"phaseOne",
			 "type":"bool"
		  },
		  {
			 "internalType":"bool",
			 "name":"phaseTwo",
			 "type":"bool"
		  },
		  {
			 "internalType":"bool",
			 "name":"phaseThree",
			 "type":"bool"
		  },
		  {
			 "internalType":"bool",
			 "name":"phaseFour",
			 "type":"bool"
		  },
		  {
			 "internalType":"bool",
			 "name":"phaseFive",
			 "type":"bool"
		  },
		  {
			 "internalType":"bool",
			 "name":"phaseSix",
			 "type":"bool"
		  }
	   ],
	   "stateMutability":"view",
	   "type":"function"
	},
	{
	   "inputs":[
		  {
			 "internalType":"address",
			 "name":"",
			 "type":"address"
		  }
	   ],
	   "name":"Customer",
	   "outputs":[
		  {
			 "internalType":"uint256",
			 "name":"tokensBought",
			 "type":"uint256"
		  },
		  {
			 "internalType":"uint256",
			 "name":"totalAmount",
			 "type":"uint256"
		  }
	   ],
	   "stateMutability":"view",
	   "type":"function"
	},
	{
	   "inputs":[
		  
	   ],
	   "name":"bnbDivider",
	   "outputs":[
		  {
			 "internalType":"uint256",
			 "name":"",
			 "type":"uint256"
		  }
	   ],
	   "stateMutability":"view",
	   "type":"function"
	},
	{
	   "inputs":[
		  
	   ],
	   "name":"buyTokens",
	   "outputs":[
		  
	   ],
	   "stateMutability":"payable",
	   "type":"function"
	},
	{
	   "inputs":[
		  {
			 "internalType":"uint256",
			 "name":"amount",
			 "type":"uint256"
		  }
	   ],
	   "name":"buyTokensWithUSDT",
	   "outputs":[
		  
	   ],
	   "stateMutability":"nonpayable",
	   "type":"function"
	},
	{
	   "inputs":[
		  {
			 "internalType":"uint256",
			 "name":"_usdtRate",
			 "type":"uint256"
		  },
		  {
			 "internalType":"uint256",
			 "name":"_bnbToUsd",
			 "type":"uint256"
		  },
		  {
			 "internalType":"uint256",
			 "name":"bnbDiv",
			 "type":"uint256"
		  },
		  {
			 "internalType":"uint256",
			 "name":"usdtDiv",
			 "type":"uint256"
		  }
	   ],
	   "name":"changeRate",
	   "outputs":[
		  
	   ],
	   "stateMutability":"nonpayable",
	   "type":"function"
	},
	{
	   "inputs":[
		  {
			 "internalType":"address payable",
			 "name":"_wallet",
			 "type":"address"
		  }
	   ],
	   "name":"changeWallet",
	   "outputs":[
		  
	   ],
	   "stateMutability":"nonpayable",
	   "type":"function"
	},
	{
	   "inputs":[
		  
	   ],
	   "name":"checkPresaleEnd",
	   "outputs":[
		  {
			 "internalType":"bool",
			 "name":"",
			 "type":"bool"
		  }
	   ],
	   "stateMutability":"view",
	   "type":"function"
	},
	{
	   "inputs":[
		  
	   ],
	   "name":"checkPresaleStatus",
	   "outputs":[
		  {
			 "internalType":"bool",
			 "name":"",
			 "type":"bool"
		  }
	   ],
	   "stateMutability":"view",
	   "type":"function"
	},
	{
	   "inputs":[
		  
	   ],
	   "name":"checkbalance",
	   "outputs":[
		  {
			 "internalType":"uint256",
			 "name":"",
			 "type":"uint256"
		  }
	   ],
	   "stateMutability":"view",
	   "type":"function"
	},
	{
	   "inputs":[
		  
	   ],
	   "name":"claimTokens",
	   "outputs":[
		  
	   ],
	   "stateMutability":"nonpayable",
	   "type":"function"
	},
	{
	   "inputs":[
		  {
			 "internalType":"uint256",
			 "name":"amount",
			 "type":"uint256"
		  }
	   ],
	   "name":"deposit",
	   "outputs":[
		  
	   ],
	   "stateMutability":"nonpayable",
	   "type":"function"
	},
	{
	   "inputs":[
		  
	   ],
	   "name":"endPresale",
	   "outputs":[
		  
	   ],
	   "stateMutability":"nonpayable",
	   "type":"function"
	},
	{
	   "inputs":[
		  
	   ],
	   "name":"getBNBPriceInUSD",
	   "outputs":[
		  {
			 "internalType":"int256",
			 "name":"",
			 "type":"int256"
		  }
	   ],
	   "stateMutability":"view",
	   "type":"function"
	},
	{
	   "inputs":[
		  
	   ],
	   "name":"getClaimableTokens",
	   "outputs":[
		  {
			 "internalType":"uint256",
			 "name":"",
			 "type":"uint256"
		  }
	   ],
	   "stateMutability":"view",
	   "type":"function"
	},
	{
	   "inputs":[
		  
	   ],
	   "name":"getDivider",
	   "outputs":[
		  {
			 "internalType":"uint256",
			 "name":"",
			 "type":"uint256"
		  }
	   ],
	   "stateMutability":"view",
	   "type":"function"
	},
	{
	   "inputs":[
		  
	   ],
	   "name":"getEndTime",
	   "outputs":[
		  {
			 "internalType":"uint256",
			 "name":"",
			 "type":"uint256"
		  }
	   ],
	   "stateMutability":"view",
	   "type":"function"
	},
	{
	   "inputs":[
		  
	   ],
	   "name":"getTokenUsdPrice",
	   "outputs":[
		  {
			 "internalType":"uint256",
			 "name":"",
			 "type":"uint256"
		  }
	   ],
	   "stateMutability":"view",
	   "type":"function"
	},
	{
	   "inputs":[
		  
	   ],
	   "name":"getUsdtDivider",
	   "outputs":[
		  {
			 "internalType":"uint256",
			 "name":"",
			 "type":"uint256"
		  }
	   ],
	   "stateMutability":"view",
	   "type":"function"
	},
	{
	   "inputs":[
		  
	   ],
	   "name":"getUsdtRate",
	   "outputs":[
		  {
			 "internalType":"uint256",
			 "name":"",
			 "type":"uint256"
		  }
	   ],
	   "stateMutability":"view",
	   "type":"function"
	},
	{
	   "inputs":[
		  
	   ],
	   "name":"owner",
	   "outputs":[
		  {
			 "internalType":"address",
			 "name":"",
			 "type":"address"
		  }
	   ],
	   "stateMutability":"view",
	   "type":"function"
	},
	{
	   "inputs":[
		  
	   ],
	   "name":"priceOracle",
	   "outputs":[
		  {
			 "internalType":"contract ChainlinkPriceOracle",
			 "name":"",
			 "type":"address"
		  }
	   ],
	   "stateMutability":"view",
	   "type":"function"
	},
	{
	   "inputs":[
		  
	   ],
	   "name":"progressBNB",
	   "outputs":[
		  {
			 "internalType":"uint256",
			 "name":"",
			 "type":"uint256"
		  }
	   ],
	   "stateMutability":"view",
	   "type":"function"
	},
	{
	   "inputs":[
		  
	   ],
	   "name":"progressUSDT",
	   "outputs":[
		  {
			 "internalType":"uint256",
			 "name":"",
			 "type":"uint256"
		  }
	   ],
	   "stateMutability":"view",
	   "type":"function"
	},
	{
	   "inputs":[
		  
	   ],
	   "name":"renounceOwnership",
	   "outputs":[
		  
	   ],
	   "stateMutability":"nonpayable",
	   "type":"function"
	},
	{
	   "inputs":[
		  
	   ],
	   "name":"soldTokens",
	   "outputs":[
		  {
			 "internalType":"uint256",
			 "name":"",
			 "type":"uint256"
		  }
	   ],
	   "stateMutability":"view",
	   "type":"function"
	},
	{
	   "inputs":[
		  
	   ],
	   "name":"startPresale",
	   "outputs":[
		  
	   ],
	   "stateMutability":"nonpayable",
	   "type":"function"
	},
	{
	   "inputs":[
		  
	   ],
	   "name":"token",
	   "outputs":[
		  {
			 "internalType":"contract IERC20",
			 "name":"",
			 "type":"address"
		  }
	   ],
	   "stateMutability":"view",
	   "type":"function"
	},
	{
	   "inputs":[
		  
	   ],
	   "name":"tokenPriceUSD",
	   "outputs":[
		  {
			 "internalType":"uint256",
			 "name":"",
			 "type":"uint256"
		  }
	   ],
	   "stateMutability":"view",
	   "type":"function"
	},
	{
	   "inputs":[
		  {
			 "internalType":"address",
			 "name":"newOwner",
			 "type":"address"
		  }
	   ],
	   "name":"transferOwnership",
	   "outputs":[
		  
	   ],
	   "stateMutability":"nonpayable",
	   "type":"function"
	},
	{
	   "inputs":[
		  
	   ],
	   "name":"usdt",
	   "outputs":[
		  {
			 "internalType":"contract IERC20",
			 "name":"",
			 "type":"address"
		  }
	   ],
	   "stateMutability":"view",
	   "type":"function"
	},
	{
	   "inputs":[
		  
	   ],
	   "name":"wallet",
	   "outputs":[
		  {
			 "internalType":"address",
			 "name":"",
			 "type":"address"
		  }
	   ],
	   "stateMutability":"view",
	   "type":"function"
	},
	{
	   "inputs":[
		  {
			 "internalType":"uint256",
			 "name":"amount",
			 "type":"uint256"
		  }
	   ],
	   "name":"withdraw",
	   "outputs":[
		  
	   ],
	   "stateMutability":"nonpayable",
	   "type":"function"
	},
	{
	   "stateMutability":"payable",
	   "type":"receive"
	}
 ]